### ISSUE TITLE
Incompatible with history v4

### ISSUE THREAD

**Issue by toblix** [taion/react-router-scroll#41]
After upgrading to v4.2.0 (or even 4.0.0) of history, I get the following error messages when gulping:
`Watchify error: Error: Cannot find module 'history/lib/DOMStateStorage' from 'C:\whatever\node_modules\scroll-behavior\lib'`
`Watchify error: Error: Cannot find module 'history/lib/Actions' from 'C:\whatever\node_modules\scroll-behavior\lib'`

**Comment by toblix** [comment]
Sorry, just realized I was looking at the wrong project.
